name: Build The Image And Publish to Docker Hub 

on: 
   push:
      branches: [ main ]
   pull_request:
      branches: [ main ]
jobs:
  build:
     runs-on: ubuntu-latest
     strategy:
       matrix :
        node-version: [18.x]
     steps:
     - uses: action/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: action/setup-node@v3
       with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
     - run: npm ci
     - run: npm run build --if-present
     - run: npm test
